In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import json

In [ ]:
f=open('/content/drive/MyDrive/Colab Notebooks/Software_5.json')

In [ ]:
list1=[]
for jsonobj in f:
  item=json.loads(jsonobj)
  list1.append(item)



In [ ]:
print(len(list1))

12805


In [ ]:
f=open("/content/drive/MyDrive/Colab Notebooks/Industrial_and_Scientific_5.json")

In [ ]:
for jsonobj in f:
  item=json.loads(jsonobj)
  list1.append(item)

In [ ]:
print(len(list1))

89876


In [ ]:
list1_sorted=sorted(list1, key = lambda i: i['unixReviewTime'])

In [ ]:
training = list1_sorted[:int(len(list1_sorted)*0.8)]

In [ ]:
test = list1_sorted[int(len(list1_sorted)*0.8):]

In [ ]:
print(len(training))

71900


In [ ]:
print(len(test))

17976


In [ ]:
print(len(list1_sorted))

89876


In [ ]:
customer=[]
product=[]
weights=[]

In [ ]:
customer_test=[]
product_test=[]
weights_test=[]

In [ ]:
for item in training:
  customer.append(item["reviewerID"])
  product.append(item["asin"])
  weights.append(item["overall"])
  

In [ ]:
for item in test:
  customer_test.append(item["reviewerID"])
  product_test.append(item["asin"])
  weights_test.append(item["overall"])

In [ ]:
# import pandas as pd
# edges_f = pd.DataFrame(
#     {
#         "source": customer,
#         "target": product,
#         "weight": weights,
#     }
# )
# edges_f
# #training edges



source      target  weight
0      A2G0O4Y8QE10AE  B00004TYCR     5.0
1       ARXU3FESTWMJJ  B00003JAU7     4.0
2       AE95Z3K6GVIC3  B00003JAU7     1.0
3      A1P4RH7KMJ1SV2  B000050HEI     5.0
4      A1P4RH7KMJ1SV2  B00003IRBV     5.0
...               ...         ...     ...
71895  A2542MY9B62WFX  B002BBGTK6     5.0
71896  A2M5BJT4R8FD3N  B003KTLRUA     5.0
71897  A17G3Z19SV8DSW  B003Y49R7G     5.0
71898  A2HBSU9AL4C9SX  B005HNX2K0     4.0
71899  A3RLNRRRMALVNO  B009ITFXDI     5.0

[71900 rows x 3 columns]

In [ ]:
import pandas as pd
edges_f = pd.DataFrame(
    {
        "source": customer,
        "target": product,
        "weight": weights,
    }
)
#training edges
edges_f.drop_duplicates(inplace=True)
edges_f=edges_f.reset_index()
edges_f


index          source      target  weight
0          0  A2G0O4Y8QE10AE  B01H3JGYYG     5.0
1          1   ARXU3FESTWMJJ  B01H3JGYYG     4.0
2          2   AE95Z3K6GVIC3  B01H3JGYYG     1.0
3          3  A1P4RH7KMJ1SV2  B01H3JGYYG     5.0
4          5  A1P4RH7KMJ1SV2  B01H3JGYYG     4.0
...      ...             ...         ...     ...
22454  71877   ANSPWMM1B66T2  B01H3JGYYG     1.0
22455  71884  A1GMUVVWD66VSB  B01H3JGYYG     2.0
22456  71887  A2B8LD7CZE4NGC  B01H3JGYYG     5.0
22457  71890  A3EME6PM4KQZSL  B01H3JGYYG     5.0
22458  71899  A3RLNRRRMALVNO  B01H3JGYYG     5.0

[22459 rows x 4 columns]

In [ ]:
import pandas as pd
edges_f_test = pd.DataFrame(
    {
        "source": customer_test,
        "target": product_test,
        "weight": weights_test,
    }
)
edges_f_test.drop_duplicates(inplace=True)
edges_f_test=edges_f_test.reset_index()
edges_f_test


index          source      target  weight
0          0  A1RRGPFH0GTADC  B00B28Z2AC     5.0
1          1  A37N7EROI8CFXL  B00BCVXUR6     5.0
2          2  A2DTSVDJIFQN68  B00BYQLGNY     1.0
3          3  A2M5BJT4R8FD3N  B00CJ5EO2E     5.0
4          4  A1RRGPFH0GTADC  B00DY9IXFI     5.0
...      ...             ...         ...     ...
17312  17971   A9CEYAGPW60CU  B01FI6IKG6     5.0
17313  17972  A1H0G18150TI9V  B01CG2HI0E     5.0
17314  17973  A2ECPIHCHXK5YB  B01EKEMNRO     5.0
17315  17974  A1NOVS56TQ8VZ3  B01H1RDJOI     3.0
17316  17975  A2U1SYP4XCIUIK  B01H3JGYYG     5.0

[17317 rows x 4 columns]

In [ ]:
revedges_f = pd.DataFrame(
    {
        "source": product,
        "target": customer,
        "weight": weights,
    }
)

revedges_f.drop_duplicates(inplace=True)
revedges_f=revedges_f.reset_index()
revedges_f

index      source          target  weight
0          0  B01H3JGYYG  A2G0O4Y8QE10AE     5.0
1          1  B01H3JGYYG   ARXU3FESTWMJJ     4.0
2          2  B01H3JGYYG   AE95Z3K6GVIC3     1.0
3          3  B01H3JGYYG  A1P4RH7KMJ1SV2     5.0
4          5  B01H3JGYYG  A1P4RH7KMJ1SV2     4.0
...      ...         ...             ...     ...
22454  71877  B01H3JGYYG   ANSPWMM1B66T2     1.0
22455  71884  B01H3JGYYG  A1GMUVVWD66VSB     2.0
22456  71887  B01H3JGYYG  A2B8LD7CZE4NGC     5.0
22457  71890  B01H3JGYYG  A3EME6PM4KQZSL     5.0
22458  71899  B01H3JGYYG  A3RLNRRRMALVNO     5.0

[22459 rows x 4 columns]

In [ ]:
revedges_f_test = pd.DataFrame(
    {
        "source": product_test,
        "target": customer_test,
        "weight": weights_test,
    }
)
revedges_f_test.drop_duplicates(inplace=True)
revedges_f_test=revedges_f_test.reset_index()
revedges_f_test

index      source          target  weight
0          0  B00B28Z2AC  A1RRGPFH0GTADC     5.0
1          1  B00BCVXUR6  A37N7EROI8CFXL     5.0
2          2  B00BYQLGNY  A2DTSVDJIFQN68     1.0
3          3  B00CJ5EO2E  A2M5BJT4R8FD3N     5.0
4          4  B00DY9IXFI  A1RRGPFH0GTADC     5.0
...      ...         ...             ...     ...
17312  17971  B01FI6IKG6   A9CEYAGPW60CU     5.0
17313  17972  B01CG2HI0E  A1H0G18150TI9V     5.0
17314  17973  B01EKEMNRO  A2ECPIHCHXK5YB     5.0
17315  17974  B01H1RDJOI  A1NOVS56TQ8VZ3     3.0
17316  17975  B01H3JGYYG  A2U1SYP4XCIUIK     5.0

[17317 rows x 4 columns]

In [ ]:
customer1=[]
product1=[]

for item in list1:
        if (item["reviewerID"] not in customer1):
          customer1.append(item["reviewerID"])
        if (item["asin"] not in product1):
          product1.append(item["asin"])

#storing list of unique cutomers and unique products in customer1 and product1 respectively.

In [ ]:
print(len(product1))
print(len(product))

6136
10


In [ ]:
customer_f = pd.DataFrame(
    index=customer1
)
customer_f



Empty DataFrame
Columns: []
Index: [A38NELQT98S4H8, A3QJU4FEN8PQSZ, ACJT8MUC0LRF0, AYUF7YETYOLNX, A31ICLWQ9CSHRS, A2BVNVJOFXGZUB, A2JMJVNTBL7K7E, A14JBDSWKPKTZA, A2WCFDOCS73PNB, A14638TGYH7GD9, A2VWE5SGNDS8HW, A13700AF4X40YG, A23E9QQHJLNGUI, A1GQRGB8FGSLIZ, A1E50L7PCVXLN4, A10Y058K7B96C6, A3V7D0LH8L7BG0, AGVWTYW0ULXHT, A31N0XY2UTB25C, A2BLFCOPSMBOZ9, A24X9HGDWV2ZZH, AHEZP9ACDYJII, A2WUYJJ7NPQ5H4, AXGLPF6X39874, AJK49DENMS2BT, A3UI63EESKUYHU, AK8GQ08WTHW4G, A1MRPX3RM48T2I, A318IDAWJ9ZYAY, ANGGNFE8DXGYC, A2N4QZL8L2NVKX, A1EMDSTJDUE6B0, A6M01NDCD957E, A3PAUB3M715CJC, AEC7B85GKPM0W, A22S7D0LP8GRDH, A3A770EP3KUHKM, A3VV6SV0Z2HNTA, A2MKY8OUI8GZG1, A3VONQL7YW8UPM, A3N7T0DY83Y4IG, AA90W95STFGAC, AHNHLGKIZ2N3B, A16QODENBJVUI1, A376OJHLE6SU9Q, A1E5WXNTI7EO2A, AEJAGHLC675A7, A17A1KTVI3DG6U, AZZ5ASC403N74, A4U27URFECK1U, A2CZ98V784SRJ0, A2GP6XJ1V3MM3L, AGOH8N902URMW, A3OIMUR42XIOFQ, A379DLIAF0MFM5, A17BUUBOU0598B, A3963R7EPE3A7E, AZYJE40XW6MFG, A3TPNC3TKGCCEI, A3G007LQX6KGOD, A3BNMHRW2R35LK, A1PI8VBCXXSGC7, A1D7VWS3DWS7X8, ATZJNEXX7LWD3, A2P6QCZWW3H1X6, A2AMTEB5UZEOXE, A3PJZ8TU8FDQ1K, A2ZJMLZ1IA2YA9, A2L6QS8SVHT9RG, A3R1WFO4KIUQXZ, A5JLAU2ARJ0BO, ACVDL5QRCOPE1, A3H7ADUP07D93H, A3FFKU2MTCOBM1, A1TR1R2QKWRSRA, A226VGZWOEBPGL, A11SWG9T60IQH8, A1T2ZO4ARVSUGE, A16RI68PS6T5CA, A1GWG5CWLKJ7ET, A1HOLE9R6WPT85, ALQ4USPEQ9L5N, A11EYMH9UV9XG7, A26LQSC65AMTGK, A2SZLNSI5KOQJT, A3LDLV1GWQJLEQ, A3LGT6UZL99IW1, A3CAG7WLTAKPI, A32B6XWNR55SRL, A38KK0SZYEH5UD, A22RY8N8CNDF3A, ARADXCOUVBS09, A11REZES0TNBSD, A3F3B6HY9RJI04, AHQRU3MRORIWQ, A1SCANWWQTEG9I, A1WBEIH7Z37LN9, A2F2S1L61X1LA9, A21OGQWFAKGC41, A1A21GIPMY89BZ, ...]

[12605 rows x 0 columns]

In [ ]:
product_f=pd.DataFrame(index=product1)
product_f

Empty DataFrame
Columns: []
Index: [0321719816, 0321700945, 0321719824, 0763855553, 0982697813, 1413313701, 1413313728, 1426296355, 1600775411, 1615354336, B00003IRBU, B00003JAU9, B00003IRBV, B00003JAU7, B00004TYCR, B00004W62O, B000050HEI, B000050ZRE, B00005AC56, B00005AFI2, B00005AFI1, B00005AFI4, B00005LBVS, B00005LVWL, B00005MOTH, B00005MOTG, B00005MOTE, B00005N6K4, B00005MOTF, B00005NCJ3, B00005NZ5Z, B00005OA45, B000066ST3, B000069IL2, B00006F7S2, B00006FI0N, B00006FI0Z, B00006J3FM, B00006OAQU, B00006ULHT, B0000AZJVC, B0000BX73E, B0000BZ54V, B0000C8XYO, B0000C8XYI, B0000C8Y0W, B0000CEM5O, B0000E6NK9, B0001F0XHE, B0001FS9NE, B0001WN16M, B0001XLSG6, B00022PTI4, B00022PTRU, B00022PTT8, B00025O87E, B0002D12D4, B0002G71T0, B0002UCSKI, B0002UCJV6, B0002ZALES, B00062VOW0, B0006460RM, B00068IBZW, B00099YLPM, B0009WA0P4, B0009X6QJM, B000A6M8QI, B000AOBSTS, B000AOGDM0, B000AP2X1E, B000B5I0O2, B000B5NS2G, B000B6N2O4, B000B8K7SG, B000BAT2TE, B000BAV2FG, B000BAWLS8, B000BQXTSS, B000BX5JQG, B000CE9IAM, B000EORV8Q, B000ES4PYU, B000FA36WY, B000FK88JK, B000GHIV2Q, B000GI0HR2, B000GHV6N2, B000GUDDXA, B000H2049I, B000HCTYTO, B000HCTY1W, B000HCTYRG, B000HCTYSA, B000HCXKLC, B000HCVR3A, B000HCVR3K, B000HCVR30, B000HCXKJY, B000HCZ9AW, ...]

[6136 rows x 0 columns]

In [ ]:
import networkx as nx
G=nx.DiGraph()

for product in product1:
  G.add_node(product)

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Copy of meta_Software.json') as f:
  for jsonObj in f:
        item = json.loads(jsonObj)
        if(G.has_node(item["asin"])):
          for x in item["also_buy"]:
            if(G.has_node(x)):
              G.add_edge(item["asin"],x)
              G.add_edge(x,item["asin"])
        

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Copy of meta_Industrial_and_Scientific.json') as f:
  for jsonObj in f:
        item = json.loads(jsonObj)
        if(G.has_node(item["asin"])):
          for x in item["also_buy"]:
            if(G.has_node(x)):
              G.add_edge(item["asin"],x)
              G.add_edge(x,item["asin"])

In [ ]:
print(G.edges)

[('0763855553', 'B0144NYGJY'), ('0763855553', 'B00HV9IM58'), ('0763855553', 'B00ZSI7Y3U'), ('B00003IRBU', 'B00003IRBV'), ('B00003IRBU', 'B000050HEI'), ('B00003IRBU', 'B0001XLSG6'), ('B00003IRBU', 'B000A6M8QI'), ('B00003IRBU', 'B000066ST3'), ('B00003IRBU', 'B0009X6QJM'), ('B00003IRBV', 'B000050HEI'), ('B00003IRBV', 'B0001XLSG6'), ('B00003IRBV', 'B00003IRBU'), ('B00003IRBV', 'B000A6M8QI'), ('B00003IRBV', 'B000066ST3'), ('B00003IRBV', 'B0009X6QJM'), ('B00003IRBV', 'B0000CEM5O'), ('B000050HEI', 'B00003IRBV'), ('B000050HEI', 'B00003IRBU'), ('B000050HEI', 'B00005LVWL'), ('B000050HEI', 'B0000CEM5O'), ('B000050HEI', 'B000A6M8QI'), ('B000050HEI', 'B000066ST3'), ('B000050HEI', 'B0009X6QJM'), ('B000050HEI', 'B00006OAQU'), ('B00005LBVS', 'B002U0L1BU'), ('B00005LVWL', 'B000050HEI'), ('B00005LVWL', 'B000066ST3'), ('B00005LVWL', 'B0009X6QJM'), ('B00005LVWL', 'B00006OAQU'), ('B00005LVWL', 'B0000CEM5O'), ('B00005LVWL', 'B0002ZALES'), ('B00005LVWL', 'B000A6M8QI'), ('B00005LVWL', 'B0001XLSG6'), ('B00005M

In [ ]:
print(len(G.edges))

60876


In [ ]:
also_buy_f=nx.to_pandas_edgelist(G)

In [ ]:
also_buy_f

source      target
0      0763855553  B0144NYGJY
1      0763855553  B00HV9IM58
2      0763855553  B00ZSI7Y3U
3      B00003IRBU  B00003IRBV
4      B00003IRBU  B000050HEI
...           ...         ...
60871  B01H3JGYYG  B00YQBBZ8A
60872  B01H3JGYYG  B00ME76OHA
60873  B01H3JGYYG  B00J0H6NNM
60874  B01H3JGYYG  B01FFV2TOS
60875  B01H3JGYYG  B01092XXD4

[60876 rows x 2 columns]

In [ ]:
G1=nx.DiGraph()
for product in product1:
  G1.add_node(product)

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Copy of meta_Software.json') as f:
  for jsonObj in f:
        item = json.loads(jsonObj)
        if(G1.has_node(item["asin"])):
          for x in item["also_view"]:
            if(G1.has_node(x)):
              G1.add_edge(item["asin"],x)
              G1.add_edge(x,item["asin"])

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Copy of meta_Industrial_and_Scientific.json') as f:
  for jsonObj in f:
        item = json.loads(jsonObj)
        if(G1.has_node(item["asin"])):
          for x in item["also_view"]:
            if(G1.has_node(x)):
              G1.add_edge(item["asin"],x)
              G1.add_edge(x,item["asin"])

In [ ]:
also_view_f=nx.to_pandas_edgelist(G1)

In [ ]:
print(also_view_f)


          source      target
0     0763855553  B00HV9IM58
1     0763855553  B0148BYIAO
2     0763855553  B0114ZV22E
3     0763855553  B0148BYIPY
4     0763855553  B011DMUIQY
...          ...         ...
7726  B010MZ8S6A  B015NDAKE4
7727  B010TWUQJ8  B01EKFVCDO
7728  B011E2VUN8  B00W5PRY52
7729  B016XMJ1XK  B00CQLORZ0
7730  B018MG4SGK  B014VM9ALM

[7731 rows x 2 columns]


In [ ]:
weights1=[]

for i in range(0,len(also_buy_f)):
  weights1.append(3)

In [ ]:
weights2=[]
for i in range(0,len(also_view_f)):
  weights2.append(3)

print(type(also_buy_f["source"]))

<class 'pandas.core.series.Series'>


In [ ]:
also_buy_f_new=pd.DataFrame(    {
        "source": list(also_buy_f["source"]),
        "target": list(also_buy_f["target"]),
        "weight": weights1,
    })
also_buy_f_new

source      target  weight
0      0763855553  B0144NYGJY       3
1      0763855553  B00HV9IM58       3
2      0763855553  B00ZSI7Y3U       3
3      B00003IRBU  B00003IRBV       3
4      B00003IRBU  B000050HEI       3
...           ...         ...     ...
60871  B01H3JGYYG  B00YQBBZ8A       3
60872  B01H3JGYYG  B00ME76OHA       3
60873  B01H3JGYYG  B00J0H6NNM       3
60874  B01H3JGYYG  B01FFV2TOS       3
60875  B01H3JGYYG  B01092XXD4       3

[60876 rows x 3 columns]

In [ ]:
also_view_f_new=pd.DataFrame(    {
        "source": list(also_view_f["source"]),
        "target": list(also_view_f["target"]),
        "weight": weights2,
    })
also_view_f_new

source      target  weight
0     0763855553  B00HV9IM58       3
1     0763855553  B0148BYIAO       3
2     0763855553  B0114ZV22E       3
3     0763855553  B0148BYIPY       3
4     0763855553  B011DMUIQY       3
...          ...         ...     ...
7726  B010MZ8S6A  B015NDAKE4       3
7727  B010TWUQJ8  B01EKFVCDO       3
7728  B011E2VUN8  B00W5PRY52       3
7729  B016XMJ1XK  B00CQLORZ0       3
7730  B018MG4SGK  B014VM9ALM       3

[7731 rows x 3 columns]

In [ ]:
edges_f


index          source      target  weight
0          0  A2G0O4Y8QE10AE  B01H3JGYYG     5.0
1          1   ARXU3FESTWMJJ  B01H3JGYYG     4.0
2          2   AE95Z3K6GVIC3  B01H3JGYYG     1.0
3          3  A1P4RH7KMJ1SV2  B01H3JGYYG     5.0
4          5  A1P4RH7KMJ1SV2  B01H3JGYYG     4.0
...      ...             ...         ...     ...
22454  71877   ANSPWMM1B66T2  B01H3JGYYG     1.0
22455  71884  A1GMUVVWD66VSB  B01H3JGYYG     2.0
22456  71887  A2B8LD7CZE4NGC  B01H3JGYYG     5.0
22457  71890  A3EME6PM4KQZSL  B01H3JGYYG     5.0
22458  71899  A3RLNRRRMALVNO  B01H3JGYYG     5.0

[22459 rows x 4 columns]

In [ ]:
import numpy as np
also_buy_f_new.index = np.arange(len(edges_f), len(edges_f)+len(also_buy_f_new))
also_buy_f_new

source      target  weight
22459  0763855553  B0144NYGJY       3
22460  0763855553  B00HV9IM58       3
22461  0763855553  B00ZSI7Y3U       3
22462  B00003IRBU  B00003IRBV       3
22463  B00003IRBU  B000050HEI       3
...           ...         ...     ...
83330  B01H3JGYYG  B00YQBBZ8A       3
83331  B01H3JGYYG  B00ME76OHA       3
83332  B01H3JGYYG  B00J0H6NNM       3
83333  B01H3JGYYG  B01FFV2TOS       3
83334  B01H3JGYYG  B01092XXD4       3

[60876 rows x 3 columns]

In [ ]:
also_view_f_new.index = np.arange(132776, 132776+len(also_view_f_new))
also_view_f_new


source      target  weight
132776  0763855553  B00HV9IM58       3
132777  0763855553  B0148BYIAO       3
132778  0763855553  B0114ZV22E       3
132779  0763855553  B0148BYIPY       3
132780  0763855553  B011DMUIQY       3
...            ...         ...     ...
140502  B010MZ8S6A  B015NDAKE4       3
140503  B010TWUQJ8  B01EKFVCDO       3
140504  B011E2VUN8  B00W5PRY52       3
140505  B016XMJ1XK  B00CQLORZ0       3
140506  B018MG4SGK  B014VM9ALM       3

[7731 rows x 3 columns]

In [ ]:
import sys
if 'google.colab' in sys.modules:
  %pip install -q stellargraph[demos]==1.2.1

In [ ]:
import stellargraph as sg

In [ ]:
from stellargraph import StellarDiGraph

In [ ]:
revedges_f

index      source          target  weight
0          0  B01H3JGYYG  A2G0O4Y8QE10AE     5.0
1          1  B01H3JGYYG   ARXU3FESTWMJJ     4.0
2          2  B01H3JGYYG   AE95Z3K6GVIC3     1.0
3          3  B01H3JGYYG  A1P4RH7KMJ1SV2     5.0
4          5  B01H3JGYYG  A1P4RH7KMJ1SV2     4.0
...      ...         ...             ...     ...
22454  71877  B01H3JGYYG   ANSPWMM1B66T2     1.0
22455  71884  B01H3JGYYG  A1GMUVVWD66VSB     2.0
22456  71887  B01H3JGYYG  A2B8LD7CZE4NGC     5.0
22457  71890  B01H3JGYYG  A3EME6PM4KQZSL     5.0
22458  71899  B01H3JGYYG  A3RLNRRRMALVNO     5.0

[22459 rows x 4 columns]

In [ ]:
levi = StellarDiGraph(
    {"product":product_f,"customer":customer_f}, edges={"c-p": edges_f,"p-c": revedges_f,"also_buy":also_buy_f_new,"also_view":also_view_f_new}
)
print(levi.info())

# all edges should have different numberings ** here revedges and edges have the same numbering 0-71900

ValueError: ignored

In [ ]:
edges_f


index          source      target  weight
0          0  A2G0O4Y8QE10AE  B01H3JGYYG     5.0
1          1   ARXU3FESTWMJJ  B01H3JGYYG     4.0
2          2   AE95Z3K6GVIC3  B01H3JGYYG     1.0
3          3  A1P4RH7KMJ1SV2  B01H3JGYYG     5.0
4          5  A1P4RH7KMJ1SV2  B01H3JGYYG     4.0
...      ...             ...         ...     ...
22454  71877   ANSPWMM1B66T2  B01H3JGYYG     1.0
22455  71884  A1GMUVVWD66VSB  B01H3JGYYG     2.0
22456  71887  A2B8LD7CZE4NGC  B01H3JGYYG     5.0
22457  71890  A3EME6PM4KQZSL  B01H3JGYYG     5.0
22458  71899  A3RLNRRRMALVNO  B01H3JGYYG     5.0

[22459 rows x 4 columns]

In [ ]:
import numpy as np
revedges_f.index = np.arange(len(edges_f), len(edges_f)+len(revedges_f))
revedges_f

index      source          target  weight
22459      0  B01H3JGYYG  A2G0O4Y8QE10AE     5.0
22460      1  B01H3JGYYG   ARXU3FESTWMJJ     4.0
22461      2  B01H3JGYYG   AE95Z3K6GVIC3     1.0
22462      3  B01H3JGYYG  A1P4RH7KMJ1SV2     5.0
22463      5  B01H3JGYYG  A1P4RH7KMJ1SV2     4.0
...      ...         ...             ...     ...
44913  71877  B01H3JGYYG   ANSPWMM1B66T2     1.0
44914  71884  B01H3JGYYG  A1GMUVVWD66VSB     2.0
44915  71887  B01H3JGYYG  A2B8LD7CZE4NGC     5.0
44916  71890  B01H3JGYYG  A3EME6PM4KQZSL     5.0
44917  71899  B01H3JGYYG  A3RLNRRRMALVNO     5.0

[22459 rows x 4 columns]

In [ ]:

also_buy_f_new.index = np.arange(len(edges_f)+len(revedges_f), len(edges_f)+len(revedges_f)+len(also_buy_f_new))
also_buy_f_new

source      target  weight
44918   0763855553  B0144NYGJY       3
44919   0763855553  B00HV9IM58       3
44920   0763855553  B00ZSI7Y3U       3
44921   B00003IRBU  B00003IRBV       3
44922   B00003IRBU  B000050HEI       3
...            ...         ...     ...
105789  B01H3JGYYG  B00YQBBZ8A       3
105790  B01H3JGYYG  B00ME76OHA       3
105791  B01H3JGYYG  B00J0H6NNM       3
105792  B01H3JGYYG  B01FFV2TOS       3
105793  B01H3JGYYG  B01092XXD4       3

[60876 rows x 3 columns]

In [ ]:
also_view_f_new.index = np.arange(len(edges_f)+len(revedges_f)+len(also_buy_f_new), len(edges_f)+len(revedges_f)+len(also_buy_f_new)+len(also_view_f_new))
also_view_f_new

source      target  weight
105794  0763855553  B00HV9IM58       3
105795  0763855553  B0148BYIAO       3
105796  0763855553  B0114ZV22E       3
105797  0763855553  B0148BYIPY       3
105798  0763855553  B011DMUIQY       3
...            ...         ...     ...
113520  B010MZ8S6A  B015NDAKE4       3
113521  B010TWUQJ8  B01EKFVCDO       3
113522  B011E2VUN8  B00W5PRY52       3
113523  B016XMJ1XK  B00CQLORZ0       3
113524  B018MG4SGK  B014VM9ALM       3

[7731 rows x 3 columns]

In [ ]:
levi = StellarDiGraph(
    {"product":product_f,"customer":customer_f}, edges={"c-p": edges_f,"p-c": revedges_f,"also_buy":also_buy_f_new,"also_view":also_view_f_new}
)
print(levi.info())


StellarDiGraph: Directed multigraph
 Nodes: 18741, Edges: 113525

 Node types:
  customer: [12605]
    Features: none
    Edge types: customer-c-p->product
  product: [6136]
    Features: none
    Edge types: product-also_buy->product, product-also_view->product, product-p-c->customer

 Edge types:
    product-also_buy->product: [60876]
        Weights: all 3
        Features: none
    product-p-c->customer: [22459]
        Weights: range=[1, 5], mean=3.96638, std=1.26865
        Features: float32 vector, length 1
    customer-c-p->product: [22459]
        Weights: range=[1, 5], mean=3.96638, std=1.26865
        Features: float32 vector, length 1
    product-also_view->product: [7731]
        Weights: all 3
        Features: none


In [ ]:
print(levi.edge_types)

Index(['also_buy', 'also_view', 'c-p', 'p-c'], dtype='object')


In [ ]:
import json
mydic={}
with open('/content/drive/MyDrive/Colab Notebooks/Copy of meta_Software.json') as f:
   for jsonObj in f:
     item = json.loads(jsonObj)
     mydic[item["asin"]]={}
     mydic[item["asin"]]["category"]=item["category"]
     mydic[item["asin"]]["brand"]=item["brand"]
    

print(mydic)



IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
print(mydic["0073513458"])

{'category': [], 'brand': 'McGraw-Hill Education'}


In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Copy of meta_Industrial_and_Scientific.json') as f:
  for jsonObj in f:
     item = json.loads(jsonObj)
     mydic[item["asin"]]={}
     mydic[item["asin"]]["category"]=item["category"]
     mydic[item["asin"]]["brand"]=item["brand"]
     


In [ ]:
print(mydic["0692782109"])

{'category': [], 'brand': 'R-Cat'}


In [ ]:
newlist=[]
for item in product1:
  if item in mydic:
    newlist.append(mydic[item])
  else:
    temp={}
    temp["category"]=[]
    temp["brand"]=""
    newlist.append(temp)



In [ ]:
print(newlist)

[{'category': [], 'brand': 'Peach Pit Press'}, {'category': [], 'brand': 'Peach Pit Press'}, {'category': [], 'brand': 'Peach Pit Press'}, {'category': ['Software', 'Business &amp; Office', 'Office Suites'], 'brand': 'Microsoft'}, {'category': ['Software', 'Education &amp; Reference', 'Religion'], 'brand': 'Immersion Digital'}, {'category': ['Software', 'Accounting &amp; Finance', 'Personal Finance', 'Money Management &amp; Budgeting'], 'brand': 'NOLO'}, {'category': ['Software', 'Business &amp; Office', 'Office Suites'], 'brand': 'NOLO'}, {'category': ['Software', 'Education &amp; Reference', 'Maps &amp; Atlases'], 'brand': 'National Geographic'}, {'category': [], 'brand': 'Topics Entertainment'}, {'category': ['Software', 'Education & Reference', 'Encyclopedias'], 'brand': 'Encyclopedia Britannica'}, {'category': ['Software', "Children's", 'Games', '</span></span></span>'], 'brand': 'by\n    \n    Her Interactive'}, {'category': ['Software', 'Operating Systems', 'Microsoft Windows'],

In [ ]:
print(product1[0])

0321719816


In [ ]:
!pip install -U scikit-learn
import sklearn
sklearn.__version__


Requirement already up-to-date: scikit-learn in /usr/local/lib/python3.7/dist-packages (0.24.1)


'0.22.2.post1'

In [ ]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
arr1=vec.fit_transform(newlist)
arr=vec.fit_transform(newlist).toarray()
print(arr
      )
arr[0][2]
print(arr1)
arr[0][194]
# vec.get_feature_names()
arr1.get_shape


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
  (0, 1271)	1.0
  (1, 1271)	1.0
  (2, 1271)	1.0
  (3, 1102)	1.0
  (3, 2233)	1.0
  (3, 2993)	1.0
  (3, 3320)	1.0
  (4, 830)	1.0
  (4, 2490)	1.0
  (4, 3179)	1.0
  (4, 3320)	1.0
  (5, 1138)	1.0
  (5, 2088)	1.0
  (5, 2939)	1.0
  (5, 3061)	1.0
  (5, 3320)	1.0
  (6, 1138)	1.0
  (6, 2233)	1.0
  (6, 2993)	1.0
  (6, 3320)	1.0
  (7, 1151)	1.0
  (7, 2490)	1.0
  (7, 2905)	1.0
  (7, 3320)	1.0
  (8, 1765)	1.0
  :	:
  (6131, 40)	1.0
  (6131, 2057)	1.0
  (6131, 2058)	1.0
  (6131, 2094)	1.0
  (6131, 2758)	1.0
  (6132, 280)	1.0
  (6132, 2542)	1.0
  (6132, 2758)	1.0
  (6132, 2987)	1.0
  (6132, 3410)	1.0
  (6133, 674)	1.0
  (6133, 2203)	1.0
  (6133, 2758)	1.0
  (6133, 2779)	1.0
  (6133, 3437)	1.0
  (6134, 40)	1.0
  (6134, 2057)	1.0
  (6134, 2058)	1.0
  (6134, 2094)	1.0
  (6134, 2758)	1.0
  (6135, 961)	1.0
  (6135, 2057)	1.0
  (6135, 2058)	1.0
  (6135, 

<bound method spmatrix.get_shape of <6136x3612 sparse matrix of type '<class 'numpy.float64'>'
	with 30264 stored elements in Compressed Sparse Row format>>

In [ ]:
arr.get_shape

AttributeError: ignored

In [ ]:
vec.feature_names_

['brand=',
 'brand=1st Choice',
 'brand=1st Web Sales',
 'brand=2-P10KIT',
 'brand=2GT Timing Belt Closed Loop',
 'brand=3-H LMOUNT',
 'brand=3-IN-ONE',
 'brand=3D',
 'brand=3D Artist Supply',
 'brand=3D CAM',
 'brand=3D Solutech',
 'brand=3D Systems',
 'brand=3D4USE',
 'brand=3DMakerWorld',
 'brand=3DPrintingSurplus',
 'brand=3DTECH',
 'brand=3DXTECH',
 'brand=3Doodler',
 'brand=3M',
 'brand=3M Dual Lock',
 'brand=3M Littmann',
 'brand=3M Vetbond',
 'brand=3dprintny.com',
 'brand=4M',
 'brand=4YourHome',
 'brand=80/20 Inc',
 'brand=A Plus Parts House',
 'brand=A World Of Deals',
 'brand=AB',
 'brand=ABN',
 'brand=ADC',
 'brand=AES Industries',
 'brand=AGPTEK',
 'brand=AIRSUNNY',
 'brand=AKOAK',
 'brand=ALAZCO',
 'brand=ALINK',
 'brand=ALUNAR',
 'brand=AMIR',
 'brand=AMX3d',
 'brand=AMZ3D',
 'brand=ANTCLABS',
 'brand=ANYCUBIC',
 'brand=ANZESER',
 'brand=ARB',
 'brand=ARES',
 'brand=ARROW FASTENER',
 'brand=ASI',
 'brand=AST Labs',
 'brand=ATD',
 'brand=ATMEL',
 'brand=ATOPLEE',
 'brand

In [ ]:
print(len(vec.feature_names_))

3612


In [ ]:
from stellargraph import IndexedArray
product_f = IndexedArray(arr, index=product1)

levi = StellarDiGraph(
    {"product":product_f,"customer":customer_f}, edges={"c-p": edges_f,"p-c": revedges_f,"also_buy":also_buy_f_new,"also_view":also_view_f_new}
)
print(levi.info())




StellarDiGraph: Directed multigraph
 Nodes: 18741, Edges: 113525

 Node types:
  customer: [12605]
    Features: none
    Edge types: customer-c-p->product
  product: [6136]
    Features: float64 vector, length 3612
    Edge types: product-also_buy->product, product-also_view->product, product-p-c->customer

 Edge types:
    product-also_buy->product: [60876]
        Weights: all 3
        Features: none
    product-p-c->customer: [22459]
        Weights: range=[1, 5], mean=3.96638, std=1.26865
        Features: float32 vector, length 1
    customer-c-p->product: [22459]
        Weights: range=[1, 5], mean=3.96638, std=1.26865
        Features: float32 vector, length 1
    product-also_view->product: [7731]
        Weights: all 3
        Features: none


In [ ]:
source,target,etype,weight=levi.edge_arrays(include_edge_type=True, include_edge_weight=True, use_ilocs=False)
print(source)
print(etype)
print(weight)
m=levi.neighbors(1822, include_edge_weight=True,use_ilocs=True)
levi.neighbors
print(m)


['0763855553' '0763855553' '0763855553' ... 'B01H3JGYYG' 'B01H3JGYYG'
 'B01H3JGYYG']
['also_buy' 'also_buy' 'also_buy' ... 'p-c' 'p-c' 'p-c']
[3. 3. 3. ... 5. 5. 5.]
[NeighbourWithWeight(node=18740, weight=1.0), NeighbourWithWeight(node=18740, weight=1.0)]


In [ ]:
ilocs=levi.edge_type_names_to_ilocs(levi.edge_types)
print(ilocs)
levi.edge_type_ilocs_to_names(ilocs)

[0 1 2 3]


array(['also_buy', 'also_view', 'c-p', 'p-c'], dtype=object)

In [ ]:
print(source)
print(etype)
print(weight)
etype_new=[]
count=0
count1=0
for i in etype:
  if i == 0:
    etype_new.append("p-p")
  if i == 1:
    etype_new.append("p-p")
  if i == 2:
    etype_new.append("c-p")
  if i == 3:
    etype_new.append("p-c") 

print(etype_new)

['0763855553' '0763855553' '0763855553' ... 'B01H3JGYYG' 'B01H3JGYYG'
 'B01H3JGYYG']
['also_buy' 'also_buy' 'also_buy' ... 'p-c' 'p-c' 'p-c']
[3. 3. 3. ... 5. 5. 5.]
[]


In [ ]:
print(len(source),len(target),len(etype_new),len(weight))

113525 113525 0 113525


In [ ]:
d={"source":source,"target":target,"edgetype":etype_new,"weight":weight}
df=pd.DataFrame(data=d)
df

ValueError: ignored

In [ ]:


compression_opts = dict(method='zip',
                        archive_name='out.csv')  
df.to_csv('out.zip', index=False,
          compression=compression_opts)  

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing, feature_extraction, model_selection
from sklearn.metrics import mean_absolute_error, mean_squared_error

import stellargraph as sg
from stellargraph.mapper import HinSAGELinkGenerator
from stellargraph.layer import HinSAGE, link_regression
from tensorflow.keras import Model, optimizers, losses, metrics

import multiprocessing
from stellargraph import datasets
from IPython.display import display, HTML
import matplotlib.pyplot as plt
%matplotlib inline

sklearn.__version__

In [ ]:
batch_size = 200
epochs = 20
# Use 70% of edges for training, the rest for testing:
train_size = 0.7
test_size = 0.3

In [ ]:
edges_f

In [ ]:
nx_G=levi.to_networkx()

In [ ]:
nx_G

In [ ]:
nx.algorithms.cluster.average_clustering(nx_G)

In [ ]:
nx.algorithms.components.number_connected_components(nx_G)

In [ ]:
nx.classes.function.density(nx_G)

In [ ]:
degrees = nx_G.degree()

In [ ]:
degree_values = dict(degrees).values()

In [ ]:
print(sum(degree_values))


In [ ]:
print(len(list(nx_G.nodes)))

In [ ]:
273862/17765


In [ ]:
edges_f_test

In [ ]:
import numpy as np
revedges_f_test.index = np.arange(len(edges_f_test), len(edges_f_test)+len(revedges_f_test))
revedges_f_test

index      source          target  weight
17317      0  B00B28Z2AC  A1RRGPFH0GTADC     5.0
17318      1  B00BCVXUR6  A37N7EROI8CFXL     5.0
17319      2  B00BYQLGNY  A2DTSVDJIFQN68     1.0
17320      3  B00CJ5EO2E  A2M5BJT4R8FD3N     5.0
17321      4  B00DY9IXFI  A1RRGPFH0GTADC     5.0
...      ...         ...             ...     ...
34629  17971  B01FI6IKG6   A9CEYAGPW60CU     5.0
34630  17972  B01CG2HI0E  A1H0G18150TI9V     5.0
34631  17973  B01EKEMNRO  A2ECPIHCHXK5YB     5.0
34632  17974  B01H1RDJOI  A1NOVS56TQ8VZ3     3.0
34633  17975  B01H3JGYYG  A2U1SYP4XCIUIK     5.0

[17317 rows x 4 columns]

In [ ]:
edges_f_test
edges_f_test.loc[edges_f_test.duplicated(), :]

Empty DataFrame
Columns: [index, source, target, weight]
Index: []

In [ ]:
revedges_f_test
revedges_f_test.loc[revedges_f_test.duplicated(), :]

Empty DataFrame
Columns: [index, source, target, weight]
Index: []

In [ ]:
from stellargraph import IndexedArray
levi_new = StellarDiGraph(
    {"product":product_f,"customer":customer_f}, edges={"c-p": edges_f_test,"p-c": revedges_f_test}
)
print(levi_new.info())


StellarDiGraph: Directed multigraph
 Nodes: 18741, Edges: 34634

 Node types:
  customer: [12605]
    Features: none
    Edge types: customer-c-p->product
  product: [6136]
    Features: float64 vector, length 3612
    Edge types: product-p-c->customer

 Edge types:
    product-p-c->customer: [17317]
        Weights: range=[1, 5], mean=4.46625, std=1.03148
        Features: float32 vector, length 1
    customer-c-p->product: [17317]
        Weights: range=[1, 5], mean=4.46625, std=1.03148
        Features: float32 vector, length 1


In [ ]:
print(len(levi_new.edges()))

34634


In [ ]:
source_test,target_test,etype_test,weight_test=levi_new.edge_arrays(include_edge_type=True, include_edge_weight=True, use_ilocs=True)

In [ ]:
print(source_test)
print(etype_test)
etype_test_new=[]

for i in etype_test:
 if i == 0:
    etype_test_new.append("c-p")
 if i == 1:
    etype_test_new.append("p-c") 
print(etype_test_new)

[ 2580  5918  8237 ... 18468 18592 18740]
[0 0 0 ... 1 1 1]
['c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', '

In [ ]:
print(len(source_test),len(target_test),len(etype_test_new),len(weight_test))

34634 34634 34634 34634


In [ ]:
d={"source":source_test,"target":target_test,"edgetype":etype_test_new,"weight":weight_test}
df=pd.DataFrame(data=d)
df

source  target edgetype  weight
0        2580   16209      c-p     5.0
1        5918   16247      c-p     5.0
2        8237   16306      c-p     1.0
3        5456   16375      c-p     5.0
4        2580   16527      c-p     5.0
...       ...     ...      ...     ...
34629   18524    4165      p-c     5.0
34630   18349    6159      p-c     5.0
34631   18468   11765      p-c     5.0
34632   18592   12041      p-c     3.0
34633   18740   10972      p-c     5.0

[34634 rows x 4 columns]

In [ ]:

compression_opts = dict(method='zip',
                        archive_name='test_noduplicates.csv')  
df.to_csv('test_noduplicates.zip', index=False,
          compression=compression_opts)  

In [ ]:
edges_f.loc[edges_f.duplicated(), :]

Empty DataFrame
Columns: [index, source, target, weight]
Index: []

In [ ]:
m=levi.neighbors("A2IE7YPWUYZAXS", include_edge_weight=True)
print(m)

[NeighbourWithWeight(node='B01H3JGYYG', weight=5.0), NeighbourWithWeight(node='B01H3JGYYG', weight=5.0), NeighbourWithWeight(node='B01H3JGYYG', weight=4.0), NeighbourWithWeight(node='B01H3JGYYG', weight=3.0), NeighbourWithWeight(node='B01H3JGYYG', weight=4.0), NeighbourWithWeight(node='B01H3JGYYG', weight=3.0)]


In [ ]:
edges_f


index          source      target  weight
0          0  A2G0O4Y8QE10AE  B01H3JGYYG     5.0
1          1   ARXU3FESTWMJJ  B01H3JGYYG     4.0
2          2   AE95Z3K6GVIC3  B01H3JGYYG     1.0
3          3  A1P4RH7KMJ1SV2  B01H3JGYYG     5.0
4          5  A1P4RH7KMJ1SV2  B01H3JGYYG     4.0
...      ...             ...         ...     ...
22454  71877   ANSPWMM1B66T2  B01H3JGYYG     1.0
22455  71884  A1GMUVVWD66VSB  B01H3JGYYG     2.0
22456  71887  A2B8LD7CZE4NGC  B01H3JGYYG     5.0
22457  71890  A3EME6PM4KQZSL  B01H3JGYYG     5.0
22458  71899  A3RLNRRRMALVNO  B01H3JGYYG     5.0

[22459 rows x 4 columns]

In [ ]:
mikasa = StellarDiGraph(
    {"product":product_f,"customer":customer_f}, edges={"c-p": edges_f,"p-c": revedges_f}
)
print(mikasa.info())
#Has only c-p and p-c edges from the training set

StellarDiGraph: Directed multigraph
 Nodes: 18741, Edges: 44918

 Node types:
  customer: [12605]
    Features: none
    Edge types: customer-c-p->product
  product: [6136]
    Features: float64 vector, length 3612
    Edge types: product-p-c->customer

 Edge types:
    product-p-c->customer: [22459]
        Weights: range=[1, 5], mean=3.96638, std=1.26865
        Features: float32 vector, length 1
    customer-c-p->product: [22459]
        Weights: range=[1, 5], mean=3.96638, std=1.26865
        Features: float32 vector, length 1


In [ ]:
source,target,etype,weight=mikasa.edge_arrays(include_edge_type=True, include_edge_weight=True, use_ilocs=True)
print(source)
print(etype)
print(weight)
ilocs=mikasa.edge_type_names_to_ilocs(mikasa.edge_types)
print(ilocs)
mikasa.edge_type_ilocs_to_names(ilocs)

[  131   130   129 ... 18740 18740 18740]
[0 0 0 ... 1 1 1]
[5. 4. 1. ... 5. 5. 5.]
[0 1]


array(['c-p', 'p-c'], dtype=object)

In [ ]:
etype_new=[]

for i in etype:
 if i == 0:
    etype_new.append("c-p")
 if i == 1:
    etype_new.append("p-c") 
print(etype_new)

['c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p', 'c-p'

In [ ]:
d={"source":source,"target":target,"edgetype":etype_new,"weight":weight}
df=pd.DataFrame(data=d)
df

source  target edgetype  weight
0         131   18740      c-p     5.0
1         130   18740      c-p     4.0
2         129   18740      c-p     1.0
3         118   18740      c-p     5.0
4         118   18740      c-p     4.0
...       ...     ...      ...     ...
44913   18740    5627      p-c     1.0
44914   18740    9576      p-c     2.0
44915   18740   11553      p-c     5.0
44916   18740    5425      p-c     5.0
44917   18740   11441      p-c     5.0

[44918 rows x 4 columns]

In [ ]:
compression_opts = dict(method='zip',
                        archive_name='train_noduplicate.csv')  
df.to_csv('train_noduplicate.zip', index=False,
          compression=compression_opts)  

In [ ]:
m=mikasa.neighbors(371, include_edge_weight=True,use_ilocs=True)

print(m)
mikasa.neighbor_arrays(1822, include_edge_weight=True, use_ilocs=True)
levi.neighbor_arrays(1822, include_edge_weight=True, use_ilocs=True)

[NeighbourWithWeight(node=18740, weight=4.0), NeighbourWithWeight(node=18740, weight=4.0), NeighbourWithWeight(node=18740, weight=5.0), NeighbourWithWeight(node=18740, weight=5.0)]


(array([18740, 18740], dtype=uint16), array([1., 1.]))

In [ ]:
edges_f.loc[edges_f.duplicated(), :]

Empty DataFrame
Columns: [index, source, target, weight]
Index: []

In [ ]:
revedges_f.loc[revedges_f.duplicated(), :]

Empty DataFrame
Columns: [index, source, target, weight]
Index: []

In [ ]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie', "Yum Yum"],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack',"cup"],
    'rating': [4, 4, 3.5, 5, 5,4]
})
df

brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack     5.0
4  Indomie  pack     5.0
5  Yum Yum   cup     4.0

In [ ]:

df.loc[df.duplicated(), :]

brand style  rating
1  Yum Yum   cup     4.0
4  Indomie  pack     5.0
5  Yum Yum   cup     4.0

In [ ]:
df.drop_duplicates()

brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack     5.0